### ISSUE TITLE
Problem when running with another dataset

### ISSUE THREAD

**Issue by cindyfu** [AllenCellModeling/pytorch_fnet#102]
I was trying to use tiff format images obtained after training and prediction (signal.tiff and target.tiff) to train the model instead of using czi format images. I created a new csv file with path_signal and path_target elements and their corresponding paths below.
 
But when I ran the training part, this error pumped out:
/home/xuecongf/.conda/envs/fnet/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, ma          y indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
Using existing train/test split.
model loaded from: saved_models/dna/model.p
fnet_nn_3d | {} | iter: 50011
History loaded from: saved_models/dna/losses.csv
/home/.../.conda/envs/fnet/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: numpy.dtype size changed, may indicate binary incompatibility. Expected 96, got 88
  return f(*args, **kwds)
buffering images:   0%|          | 0/30 [00:00<?, ?it/s]
<fnet.data.tiffdataset.TiffDataset object at 0x2b3ebbc2cf60>

Traceback (most recent call last):
File "train_model.py", line 161, in <module>
    main()
 File "train_model.py", line 112, in main
    dataloader_train = get_dataloader(n_remaining_iterations, opts)
  File "train_model.py", line 31, in get_dataloader
    **opts.bpds_kwargs,
  File "/home/…/pytorch_fnet/fnet/data/bufferedpatchdataset.py", line 55, in __init__
    datum = dataset[datum_index]
  File "/home/…/pytorch_fnet/fnet/data/tiffdataset.py", line 49, in __getitem__
    im_out[0] = t(im_out[0])
  File "/home/…/pytorch_fnet/fnet/transforms.py", line 193, in __call__
    return scipy.ndimage.zoom(x, (self.factors), mode='nearest')
  File "/home/…/.conda/envs/fnet/lib/python3.6/site-packages/scipy/ndimage/interpolation.py", line 573, in zoom
    zoom = _ni_support._normalize_sequence(zoom, input.ndim)
  File "/home/…/.conda/envs/fnet/lib/python3.6/site-packages/scipy/ndimage/_ni_support.py", line 65, in _normalize_sequence
    raise RuntimeError(err)
RuntimeError: sequence argument must have length equal to input rank
 
[csv&bashscript.zip](https://github.com/AllenCellModeling/pytorch_fnet/files/2728513/csv.bashscript.zip)

**Comment by cindyfu** [comment]
The error occurs because while calling get_image of TifReader class, the dimension of the output is 4, with the length of 1 when axis=0. Therefore it causes a difference between the shape and the rank of input of Resizer (which has a dimension of 3). I am not sure whether it is due to the different versions of io.
The issue can be solved by adding a line of code to the end of __init__ in tifreader.py:
`self.tif_np = np.squeeze(self.tif_np, axis = 0)`

**Comment by NiklasTR** [comment]
Hi @cindyfu, do you mind sharing you version of the __init__ for tifreaderpy?
My current modification looks like this: 
![image](https://user-images.githubusercontent.com/18559148/56831202-83301580-6836-11e9-889e-a53a77320514.png)

Which does not solve the problem, but causes: `ValueError: cannot select an axis to squeeze out which has size not equal to one`

**Comment by cindyfu** [comment]
> Hi @cindyfu, do you mind sharing you version of the **init** for tifreaderpy?
> My current modification looks like this:
> ![image](https://user-images.githubusercontent.com/18559148/56831202-83301580-6836-11e9-889e-a53a77320514.png)
> 
> Which does not solve the problem, but causes: `ValueError: cannot select an axis to squeeze out which has size not equal to one`

Sorry for the late reply. My init is exactly the same as yours.
