### ISSUE TITLE
Syntax eror in test script

### ISSUE THREAD

**Issue by lab9001** [AllenCellModeling/pytorch_fnet#106]
Hello there, we are experiencing a syntax error while testing the test script. Do you guys have any ideas? Thank you very much in advance
File "scripts/train_model.py", line 3
    DATASET = ${1:-dna}
              ^
SyntaxError: invalid syntax
---- script:
#!/bin/bash -x

DATASET=${1:-dna}
N_ITER=50000
RUN_DIR="saved_models/${DATASET}"
PATH_DATASET_ALL_CSV="data/csvs/${DATASET}.csv"
PATH_DATASET_TRAIN_CSV="data/csvs/${DATASET}/train.csv"
GPU_IDS=${2:-0}

**Comment by lab9001** [comment]
And one further question: The train_model.sh is obviously a shell script and we startet is as a shell script. However, within the script it says " python scripts/train_model.py". Does it mean it swichtes to python? Also, there is no scripts/train_model.py file for download? Thanks a lot for your help!

**Comment by counkomol** [comment]
The file name implies it is a Python script, but that doesn't look like Python.
