### ISSUE TITLE
RuntimeError: sequence argument must have length equal to input rank

### ISSUE THREAD

**Issue by NiklasTR** [AllenCellModeling/pytorch_fnet#119]
I am running the *release_1* branch on a custom dataset for the first time on an Ubuntu18 AWS P3 instance. I created a conda enviromnent acc. to the instructions and had a successful run of the example script. 

When starting the training of a new dataset with the following shell scripts: 
`source scripts/train_model_example.sh 000012049003_test 0`
I receive the following error: 
`RuntimeError: sequence argument must have length equal to input rank`

![image](https://user-images.githubusercontent.com/18559148/56831944-80cebb00-6838-11e9-842e-17665aaaf032.png)

I tried a fix proposed in #102, but without success. 

This is my csv file: 
path_signal,path_target
bucket/flatfield/000012048903__2019-02-06T20_33_15-Measurement_2/000012048903__2019-02-06T20_33_15-Measurement_2-sk1-A01-f01-ch2/r01c01f01p07-ch2sk1fk1fl1_flatfield.tiff,bucket/flatfi$
bucket/flatfield/000012048903__2019-02-06T20_33_15-Measurement_2/000012048903__2019-02-06T20_33_15-Measurement_2-sk1-A02-f01-ch2/r01c01f01p07-ch2sk1fk1fl1_flatfield.tiff,bucket/flatfi$
bucket/flatfield/000012048903__2019-02-06T20_33_15-Measurement_2/000012048903__2019-02-06T20_33_15-Measurement_2-sk1-A03-f01-ch2/r01c01f01p07-ch2sk1fk1fl1_flatfield.tiff,bucket/flatfi$

and here is my shell script: 
#!/bin/bash -x
DATASET=${1:-dna}
N_ITER=50000
BUFFER_SIZE=30
BATCH_SIZE=24
RUN_DIR="saved_models/${DATASET}"
PATH_DATASET_ALL_CSV="data/csvs/${DATASET}.csv"
PATH_DATASET_TRAIN_CSV="data/csvs/${DATASET}/train.csv"
GPU_IDS=${2:-0}

cd $(cd "$(dirname ${BASH_SOURCE})" && pwd)/..

python scripts/python/split_dataset.py ${PATH_DATASET_ALL_CSV} "data/csvs" --train_size 0.75 -v
python train_model.py \
       --n_iter ${N_ITER} \
       --class_dataset TiffDataset \
       --path_dataset_csv ${PATH_DATASET_TRAIN_CSV} \
       --buffer_size ${BUFFER_SIZE} \
       --buffer_switch_frequency 2000000 \
       --batch_size ${BATCH_SIZE} \
       --path_run_dir ${RUN_DIR} \
       --gpu_ids ${GPU_IDS}

**Comment by NiklasTR** [comment]
I did some digging, the error seems to be caused by a misalignment during the normalization step of pre-processing.  [link to code](https://github.com/AllenCellModeling/pytorch_fnet/blob/20e97b2234e91abf75ef5cd451a03d9d0fb9d761/fnet/data/tiffdataset.py#L34).

**Comment by counkomol** [comment]
I'm glad you figured it out! :)

**Comment by NiklasTR** [comment]
Hi @counkomol actually I still don't have a solution - just tried to help identify the cause of the error. Do you know how to fix this problem?
