### ISSUE TITLE
Update BufferedPatchDataset

### ISSUE THREAD

**Issue by counkomol** [AllenCellModeling/pytorch_fnet#130]
There are several issues with BufferedPatchDataset (bpds) that need to be addressed:

- It is currently not covered by a test.
- The `buffer_switch_frequency` parameter is confusing. The parameter value is used as an interval/period, not a frequency.
- The `npatches` parameter is arbitrary. A bpds object really has no "length" in the traditional sense.
- It uses a standard Python list to implement a queue, which is sub-optimal.
- It is a subclass of `FnetDataset`, yet does not use the underlying methods/attributes of `FnetDataset`.
- It is not truly a dataset:
    - It's `__len__` is meaningless as mentioned above.
    - It's `__getitem__` is random.
- There is a bug where the first buffer swap occurs too early.
- The documentation generally needs to be improved.
- The public attribute `self.remaining_to_be_in_buffer` is unused and misleading when `shuffle_images` is set to False.

**Comment by gregjohnso** [comment]
Closing issue as it is marked as done
