### ISSUE TITLE
problem with botocore\quilt 3

### ISSUE THREAD

**Issue by SmoliKat** [AllenCellModeling/pytorch_fnet#149]
Hello Greg,I have tried to train the example today and it appears that there is some problem with quilt 3 installation (apparently there is some issue with "botocore", see the attached file and link)
Link to botocore issue:https://github.com/boto/botocore/issues/1872
Are you familiar with this issue? 
<img width="688" alt="error while installing quilt" src="https://user-images.githubusercontent.com/11944209/69157466-a03b7700-0aed-11ea-9bbc-1bceb09c1b30.PNG">

**Comment by JacksonMaxfield** [comment]
@SmoliKat This is an issue on the data storage / distribution side. Quilt is releasing a new package version later today that should fix this. Once that happens you should simply be able to reinstall the package and it should fix itself. Will keep you posted when that happens.

**Comment by gregjohnso** [comment]
@SmoliKat Please re-pull the master branch and reinstall. It should be fixed.
