### ISSUE TITLE
2D data collection as .csv

### ISSUE THREAD

**Issue by gregjohnso** [AllenCellModeling/pytorch_fnet#16]

**Comment by fcollman** [comment]
I will own this.

**Comment by fcollman** [comment]
I believe this is done..

[forrestc@qmaster IF_to_EM_testdata]$ find  $PWD/*.csv
/allen/aics/modeling/data/IF_to_EM_testdata/LMlow.csv
/allen/aics/modeling/data/IF_to_EM_testdata/LMmed.csv
