### ISSUE TITLE
question about the data 

### ISSUE THREAD

**Issue by Cptmaxon** [AllenCellModeling/pytorch_fnet#177]
I'm trying to understand the metadata.csv file from quilt. but the readme doesn't really explain what the FOV image contains. it has 7 channels, I understand one is brightfield and the other is the structure , but what about the extra 5? 
thanks in advance 
if you can point me to someone who can help , that would be amazing.

**Comment by JacksonMaxfield** [comment]
Hey @Cptmaxon 

From the README:
"Each field of view (FOV) includes 4 channels (BF, EGFP, DNA, Cell membrane)"

However, that does indeed miss that there are seven channels in some images. These are extra dummy channels added during image acquisition.

We recommend using the metadata for each image to know which channel is which, with `aicsimageio` that is as simple as:
```python
from aicsimageio import AICSImage

img = AICSImage("my_file.ome.tiff")
img.get_channel_names()
```
[Link to `get_channel_names` doc](https://allencellmodeling.github.io/aicsimageio/aicsimageio.html#aicsimageio.aics_image.AICSImage.get_channel_names)

(Use whatever image reading library you would like, I just know `aicsimageio` best as I am a maintainer)

You will be able to know which channels are dummy channels both visibly when loaded in an image viewer or if they have an `_` in their channel name metadata value, i.e. `H3342` is the valid channel for Hoechst dye to stain DNA, while`H3342_1` or `H3342_2` -- the `_1` or `_2` mean it is a dummy channel.

Hope this helps! Let me know if you have any other questions.

**Comment by Cptmaxon** [comment]
hmm haven't seen that in the readme, thank you so much!

**Comment by JacksonMaxfield** [comment]
Sorry. By README I meant the [Quilt data package README](https://open.quiltdata.com/b/allencell/packages/aics/pipeline_integrated_cell) not this repo. My bad!
