### ISSUE TITLE
Move *.py files (except setup.py) into fnet directory

### ISSUE THREAD

**Issue by counkomol** [AllenCellModeling/pytorch_fnet#41]

**Comment by gregjohnso** [comment]
Including `model_modules` and maybe `aicsimage`?

**Comment by counkomol** [comment]
Hmm...sure.... Hopefully aicsimage will not cause problems.

**Comment by fcollman** [comment]
I vote that we push on making aicsimage open source and an external dependancy on the project, push it to pypi and remove it from this code base.  It will be a nightmare if we include it in this code base but then things start diverging.
