### ISSUE TITLE
make pre prediction cropping, and post prediction pad with zero

### ISSUE THREAD

**Issue by fcollman** [AllenCellModeling/pytorch_fnet#66]
make test time dataset that has cropping and padding options that make the prediction the same size as the output.   

test time model input modification options... pad/crop width and height parameters (can be negative to crop, positive to pad), default is to crop down to the nearest 16 option. 
at test time output .. reverse operation of test time modifications. 

modify dataset object to have these crop options/choices recorded, modify dataset class to have function to reverse this operation. 

needs to be done before #62

**Comment by counkomol** [comment]
Addressed with #68.

Instead of modifying the Dataset class, a cropper/padder object stores and can "undo" its last action.
