### ISSUE TITLE
Docker build doesn't work, build script also not executable

### ISSUE THREAD

**Issue by fcollman** [AllenCellModeling/pytorch_fnet#9]
pytorch-cudnnv6 is not an image on dockerhub, just a tag referenced from the pytorch repo.  https://github.com/apaszke/pytorch-dist#docker-image.  Should be rewritten to just work..

**Comment by fcollman** [comment]
more problems in the same vein...

scripts are not executable in repo
running the test script in the Dockerifle gives the error 
ModuleNotFoundError: No module named 'fnet.data.transforms'

this is presumably because the docker build hasn't put the data in the pythonpath.

really the package should have a setup.py probably.

**Comment by fcollman** [comment]
This is addressed by #10

**Comment by counkomol** [comment]
I'm seeing this issue when running the build script:

Step 7/16 : RUN pip install -y tifffile==0.12.1
 ---> Running in c37d9f725cc3

Usage:
  pip install [options] <requirement specifier> [package-index-options] ...
  pip install [options] -r <requirements file> [package-index-options] ...
  pip install [options] [-e] <vcs project url> ...
  pip install [options] [-e] <local project path> ...
  pip install [options] <archive url/path> ...

no such option: -y
The command '/bin/sh -c pip install -y tifffile==0.12.1' returned a non-zero code: 2

**Comment by gregjohnso** [comment]
(Hopefully) resolved with commit 16b46e568d7a30bf5f871d55b65d31428bf1040

**Comment by gregjohnso** [comment]
(Hopefully) resolved with commit 16b46e5
