### ISSUE TITLE
pip install doesn't install submodules

### ISSUE THREAD

**Issue by JacksonMaxfield** [AllenCellModeling/pytorch_fnet#96]
`pip install git+https://github.com/AllenCellModeling/pytorch_fnet.git` will install the base modules but does not install `fnet.nn_modules` for instance.

`import fnet` works and imports the module and the defined imports from its `__init__.py`

`import fnet.nn_modules` fails due to two things:

1) `setup.py` needs to use `packages=find_packages(exclude=['doc/*', 'docker/*', 'data/*', 'scripts/*', 'tests/*'])`

2) Create an `__init__.py` file for the `nn_modules` submodule, and for all submodules you want to include in the final package structured as so:
```python
from . import fnet_nn_2d
from . import fnet_nn_3d
```

Discovered while trying to implement something similar to the `predict.py` script in the base directory.

**Comment by counkomol** [comment]
I believe this should no longer be an issue because `__init__.py` have been added to relevant submodules.
